"""
Train a MONAI U-Net for RBC cell segmentation against the pseudo-masks
generated by data_prep.py.

IMPORTANT (see data_prep.py docstring): these masks are fixed-radius
circles around point annotations, not true cell-boundary ground truth --
Chula-RBC-12 ships no real segmentation masks. IoU reported here is IoU
against our own synthetic masks, not against verified cell boundaries.
State this plainly in the README/video. It's still a legitimate weak-
supervision approach (the same trick classical cell-counting pipelines
use), just don't imply pixel-perfect ground truth where none exists.

Input:  data/raw/Dataset/*.jpg              (full smear images)
        data/processed/masks/*_mask.png     (from data_prep.py)
Output: models/unet_seg.pt                  (checkpoint)
"""

import argparse
from pathlib import Path

import torch
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms as T
from PIL import Image
import numpy as np

from monai.networks.nets import UNet
from monai.losses import DiceLoss
from monai.metrics import MeanIoU


class RBCSegDataset(Dataset):
    """
    Pairs each full smear image with its pseudo-mask.
    Expects mask files named '<image_stem>_mask.png' in masks_dir,
    matching image files (any extension) in images_dir.
    """

    def __init__(self, images_dir: str, masks_dir: str, image_size=(256, 256)):
        self.images_dir = Path(images_dir)
        self.masks_dir = Path(masks_dir)
        self.image_size = image_size

        mask_files = sorted(self.masks_dir.glob("*_mask.png"))
        self.pairs = []
        for mask_path in mask_files:
            stem = mask_path.name[: -len("_mask.png")]
            matches = list(self.images_dir.glob(f"{stem}.*"))
            if matches:
                self.pairs.append((matches[0], mask_path))

        if not self.pairs:
            raise FileNotFoundError(
                f"No matching image/mask pairs found between {images_dir} and {masks_dir}. "
                "Run data_prep.py first."
            )

        self.img_transform = T.Compose([
            T.Resize(image_size),
            T.ToTensor(),  # -> [3, H, W], float in [0, 1]
        ])
        self.mask_transform = T.Compose([
            T.Resize(image_size, interpolation=T.InterpolationMode.NEAREST),
        ])

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        image_path, mask_path = self.pairs[idx]
        image = Image.open(image_path).convert("RGB")
        mask = Image.open(mask_path).convert("L")

        image = self.img_transform(image)
        mask = self.mask_transform(mask)
        mask = torch.from_numpy(np.array(mask, dtype=np.float32) / 255.0).unsqueeze(0)
        mask = (mask > 0.5).float()  # binarize after resize interpolation

        return image, mask


def build_model():
    return UNet(
        spatial_dims=2,
        in_channels=3,
        out_channels=1,
        channels=(16, 32, 64, 128, 256),
        strides=(2, 2, 2, 2),
        num_res_units=2,
    )


def train(data_root: str, out_path: str, epochs: int = 20, batch_size: int = 4,
          lr: float = 1e-3, image_size=(256, 256), val_fraction: float = 0.15,
          device: str = None):
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")

    dataset = RBCSegDataset(
        images_dir=f"{data_root}/raw/Dataset",
        masks_dir=f"{data_root}/processed/masks",
        image_size=image_size,
    )

    val_size = max(1, int(len(dataset) * val_fraction))
    train_size = len(dataset) - val_size
    train_ds, val_ds = random_split(dataset, [train_size, val_size])

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)

    model = build_model().to(device)
    loss_fn = DiceLoss(sigmoid=True)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    iou_metric = MeanIoU(include_background=False)

    best_iou = -1.0
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, epochs + 1):
        model.train()
        train_loss = 0.0
        for images, masks in train_loader:
            images, masks = images.to(device), masks.to(device)
            optimizer.zero_grad()
            preds = model(images)
            loss = loss_fn(preds, masks)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * images.size(0)
        train_loss /= len(train_ds)

        model.eval()
        iou_metric.reset()
        with torch.no_grad():
            for images, masks in val_loader:
                images, masks = images.to(device), masks.to(device)
                preds = (torch.sigmoid(model(images)) > 0.5).float()
                iou_metric(y_pred=preds, y=masks)
        val_iou = iou_metric.aggregate().item()

        print(f"epoch {epoch:3d}/{epochs}  train_loss={train_loss:.4f}  val_IoU={val_iou:.4f}")

        if val_iou > best_iou:
            best_iou = val_iou
            torch.save({"model_state": model.state_dict(), "val_iou": val_iou}, out_path)

    print(f"Best val IoU (against pseudo-masks): {best_iou:.4f} -- saved to {out_path}")
    return best_iou


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", default="../data")
    parser.add_argument("--out", default="../models/unet_seg.pt")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-3)
    args = parser.parse_args()

    train(args.data_root, args.out, epochs=args.epochs, batch_size=args.batch_size, lr=args.lr)
