"""
Export trained segmentation (U-Net) and classification (EfficientNet-B0)
models to ONNX for in-browser inference via ONNX.js.

Also writes ml/MODEL_IO.md with the real, final tensor shapes -- the web
side integrates against that file, not this script or the training code.

Usage:
    python export_onnx.py \
        --seg-checkpoint ../models/unet_seg.pt \
        --cls-checkpoint ../models/efficientnet_b0.pt \
        --web-models-dir ../../web/public/models
"""

import argparse
import shutil
from pathlib import Path
from datetime import date

import torch
import onnx
import onnxruntime as ort
import numpy as np

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from segmentation.train_unet import build_model as build_unet  # noqa: E402
from classification.train_efficientnet import build_model as build_efficientnet, CLASS_LIST  # noqa: E402

SEG_IMAGE_SIZE = 256   # must match train_unet.py's image_size
CLS_IMAGE_SIZE = 224   # must match train_efficientnet.py's image_size


def export_segmentation_model(checkpoint_path: str, out_path: str):
    model = build_unet()
    ckpt = torch.load(checkpoint_path, map_location="cpu")
    model.load_state_dict(ckpt["model_state"])
    model.eval()

    dummy_input = torch.randn(1, 3, SEG_IMAGE_SIZE, SEG_IMAGE_SIZE)

    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    torch.onnx.export(
        model, dummy_input, out_path,
        input_names=["image"], output_names=["mask_logits"],
        dynamic_axes={"image": {0: "batch"}, "mask_logits": {0: "batch"}},
        opset_version=18,
    )

    _verify_onnx(out_path, dummy_input, model, output_key="mask_logits")
    print(f"Segmentation exported: {out_path} (val_IoU at export time: {ckpt.get('val_iou', 'unknown')})")
    return {
        "input_shape": [1, 3, SEG_IMAGE_SIZE, SEG_IMAGE_SIZE],
        "input_dtype": "float32",
        "output": "single-channel logits, same H/W as input; apply sigmoid then threshold >0.5 for binary mask",
    }


def export_classification_model(checkpoint_path: str, out_path: str):
    model = build_efficientnet(pretrained=False)
    ckpt = torch.load(checkpoint_path, map_location="cpu")
    model.load_state_dict(ckpt["model_state"])
    model.eval()

    dummy_input = torch.randn(1, 3, CLS_IMAGE_SIZE, CLS_IMAGE_SIZE)

    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    torch.onnx.export(
        model, dummy_input, out_path,
        input_names=["cell_crop"], output_names=["class_logits"],
        dynamic_axes={"cell_crop": {0: "batch"}, "class_logits": {0: "batch"}},
        opset_version=18,
    )

    _verify_onnx(out_path, dummy_input, model, output_key="class_logits")
    print(f"Classification exported: {out_path} (val_macro_F1 at export time: {ckpt.get('val_macro_f1', 'unknown')})")
    return {
        "input_shape": [1, 3, CLS_IMAGE_SIZE, CLS_IMAGE_SIZE],
        "input_dtype": "float32",
        "normalization": "ImageNet mean/std: mean=[0.485,0.456,0.406] std=[0.229,0.224,0.225]",
        "output": f"{len(CLASS_LIST)}-length logits, apply softmax; class order below",
        "class_order": ckpt.get("class_list", CLASS_LIST),
    }


def _verify_onnx(onnx_path: str, dummy_input: torch.Tensor, torch_model, output_key: str, atol=1e-4):
    """Sanity check: ONNX Runtime output must match the PyTorch model's output on the same input."""
    onnx_model = onnx.load(onnx_path)
    onnx.checker.check_model(onnx_model)

    with torch.no_grad():
        torch_out = torch_model(dummy_input).numpy()

    sess = ort.InferenceSession(onnx_path)
    input_name = sess.get_inputs()[0].name
    ort_out = sess.run(None, {input_name: dummy_input.numpy()})[0]

    max_diff = np.abs(torch_out - ort_out).max()
    if max_diff > atol:
        raise RuntimeError(
            f"ONNX/PyTorch output mismatch for {onnx_path}: max abs diff {max_diff} > {atol}. "
            "Do not ship this export -- investigate before deploying."
        )
    print(f"  verified: ONNX output matches PyTorch (max abs diff {max_diff:.2e})")


def write_model_io_doc(seg_info: dict, cls_info: dict, out_path: str):
    class_lines = "\n".join(f"  {i}. {name}" for i, name in enumerate(cls_info["class_order"]))
    content = f"""# Model I/O Contract

Auto-generated by export_onnx.py on {date.today().isoformat()}. The web side
integrates against this file -- if you retrain and re-export, this file is
regenerated too; don't hand-edit shapes here without re-running the export.

## `segmentation.onnx`

- **Input tensor shape:** {seg_info['input_shape']} (NCHW)
- **Input dtype:** {seg_info['input_dtype']}
- **Preprocessing:** resize to {SEG_IMAGE_SIZE}x{SEG_IMAGE_SIZE}, scale pixel values to [0, 1], no other normalization
- **Output:** {seg_info['output']}
- **Note:** trained against pseudo-masks (fixed-radius circles around point annotations, not true cell boundaries -- see ml/src/data_prep.py docstring). State this in the demo/README.

## `classification.onnx`

- **Input tensor shape:** {cls_info['input_shape']} (NCHW)
- **Input dtype:** {cls_info['input_dtype']}
- **Preprocessing:** resize to {CLS_IMAGE_SIZE}x{CLS_IMAGE_SIZE}, scale to [0,1], then normalize: {cls_info['normalization']}
- **Output:** {cls_info['output']}
- **Class order (index -> class):**
{class_lines}

## Verification

Both exports are checked at export time: ONNX Runtime output is compared against the original PyTorch model's output on the same random input (max abs diff must be < 1e-4). If export_onnx.py completed without raising an error, this check passed.
"""
    Path(out_path).write_text(content)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seg-checkpoint", default="../models/unet_seg.pt")
    parser.add_argument("--cls-checkpoint", default="../models/efficientnet_b0.pt")
    parser.add_argument("--onnx-out-dir", default="../models/onnx")
    parser.add_argument("--web-models-dir", default="../../web/public/models")
    parser.add_argument("--model-io-doc", default="../MODEL_IO.md")
    args = parser.parse_args()

    seg_onnx_path = f"{args.onnx_out_dir}/segmentation.onnx"
    cls_onnx_path = f"{args.onnx_out_dir}/classification.onnx"

    seg_info = export_segmentation_model(args.seg_checkpoint, seg_onnx_path)
    cls_info = export_classification_model(args.cls_checkpoint, cls_onnx_path)

    write_model_io_doc(seg_info, cls_info, args.model_io_doc)

    Path(args.web_models_dir).mkdir(parents=True, exist_ok=True)
    for onnx_path in (seg_onnx_path, cls_onnx_path):
        dest = Path(args.web_models_dir) / Path(onnx_path).name
        if Path(onnx_path).resolve() == dest.resolve():
            print(f"{onnx_path} already at destination, skipping copy")
        else:
            shutil.copy(onnx_path, dest)
    print(f"ONNX files ready in {args.web_models_dir}")
